# Simple workflow for deploying static content to GitHub Pages
name: Health Pull Request

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  # single check commit
  check:
    runs-on: ubuntu-latest
    env: 
      BASE_URL: /FCC-frontend-projects
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test -- run
      - name: Build
        run: npm run build
